language: c

script: ./tests/test.sh

os:
    - linux
    - osx

sudo: false

notifications:
    irc:
        channels: "irc.freenode.net#plof"
        template: "%{repository} (%{branch} - %{commit} : %{author}): %{message}"
