struct GGGGC_PStack1 { void *next; void **ptrs[1]; void *term; };
struct GGGGC_PStack2 { void *next; void **ptrs[2]; void *term; };
struct GGGGC_PStack3 { void *next; void **ptrs[3]; void *term; };
struct GGGGC_PStack4 { void *next; void **ptrs[4]; void *term; };
struct GGGGC_PStack5 { void *next; void **ptrs[5]; void *term; };
struct GGGGC_PStack6 { void *next; void **ptrs[6]; void *term; };
struct GGGGC_PStack7 { void *next; void **ptrs[7]; void *term; };
struct GGGGC_PStack8 { void *next; void **ptrs[8]; void *term; };
struct GGGGC_PStack9 { void *next; void **ptrs[9]; void *term; };
struct GGGGC_PStack10 { void *next; void **ptrs[10]; void *term; };
struct GGGGC_PStack11 { void *next; void **ptrs[11]; void *term; };
struct GGGGC_PStack12 { void *next; void **ptrs[12]; void *term; };
struct GGGGC_PStack13 { void *next; void **ptrs[13]; void *term; };
struct GGGGC_PStack14 { void *next; void **ptrs[14]; void *term; };
struct GGGGC_PStack15 { void *next; void **ptrs[15]; void *term; };
struct GGGGC_PStack16 { void *next; void **ptrs[16]; void *term; };
struct GGGGC_PStack17 { void *next; void **ptrs[17]; void *term; };
struct GGGGC_PStack18 { void *next; void **ptrs[18]; void *term; };
struct GGGGC_PStack19 { void *next; void **ptrs[19]; void *term; };
struct GGGGC_PStack20 { void *next; void **ptrs[20]; void *term; };
#define GGC_PUSH1(_obj1) do { struct GGGGC_PStack1 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack1)); struct GGGGC_PStack1 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH2(_obj1, _obj2) do { struct GGGGC_PStack2 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack2)); struct GGGGC_PStack2 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH3(_obj1, _obj2, _obj3) do { struct GGGGC_PStack3 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack3)); struct GGGGC_PStack3 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH4(_obj1, _obj2, _obj3, _obj4) do { struct GGGGC_PStack4 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack4)); struct GGGGC_PStack4 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH5(_obj1, _obj2, _obj3, _obj4, _obj5) do { struct GGGGC_PStack5 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack5)); struct GGGGC_PStack5 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH6(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6) do { struct GGGGC_PStack6 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack6)); struct GGGGC_PStack6 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH7(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7) do { struct GGGGC_PStack7 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack7)); struct GGGGC_PStack7 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH8(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8) do { struct GGGGC_PStack8 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack8)); struct GGGGC_PStack8 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH9(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9) do { struct GGGGC_PStack9 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack9)); struct GGGGC_PStack9 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH10(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10) do { struct GGGGC_PStack10 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack10)); struct GGGGC_PStack10 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH11(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11) do { struct GGGGC_PStack11 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack11)); struct GGGGC_PStack11 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH12(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12) do { struct GGGGC_PStack12 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack12)); struct GGGGC_PStack12 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH13(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13) do { struct GGGGC_PStack13 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack13)); struct GGGGC_PStack13 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH14(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13, _obj14) do { struct GGGGC_PStack14 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack14)); struct GGGGC_PStack14 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), (void **) &(_obj14), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH15(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13, _obj14, _obj15) do { struct GGGGC_PStack15 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack15)); struct GGGGC_PStack15 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), (void **) &(_obj14), (void **) &(_obj15), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH16(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13, _obj14, _obj15, _obj16) do { struct GGGGC_PStack16 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack16)); struct GGGGC_PStack16 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), (void **) &(_obj14), (void **) &(_obj15), (void **) &(_obj16), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH17(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13, _obj14, _obj15, _obj16, _obj17) do { struct GGGGC_PStack17 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack17)); struct GGGGC_PStack17 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), (void **) &(_obj14), (void **) &(_obj15), (void **) &(_obj16), (void **) &(_obj17), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH18(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13, _obj14, _obj15, _obj16, _obj17, _obj18) do { struct GGGGC_PStack18 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack18)); struct GGGGC_PStack18 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), (void **) &(_obj14), (void **) &(_obj15), (void **) &(_obj16), (void **) &(_obj17), (void **) &(_obj18), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH19(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13, _obj14, _obj15, _obj16, _obj17, _obj18, _obj19) do { struct GGGGC_PStack19 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack19)); struct GGGGC_PStack19 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), (void **) &(_obj14), (void **) &(_obj15), (void **) &(_obj16), (void **) &(_obj17), (void **) &(_obj18), (void **) &(_obj19), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
#define GGC_PUSH20(_obj1, _obj2, _obj3, _obj4, _obj5, _obj6, _obj7, _obj8, _obj9, _obj10, _obj11, _obj12, _obj13, _obj14, _obj15, _obj16, _obj17, _obj18, _obj19, _obj20) do { struct GGGGC_PStack20 *_ggggc_func_pstack = alloca(sizeof(struct GGGGC_PStack20)); struct GGGGC_PStack20 _ggggc_func_pstack_tmp = { ggggc_pstack, (void **) &(_obj1), (void **) &(_obj2), (void **) &(_obj3), (void **) &(_obj4), (void **) &(_obj5), (void **) &(_obj6), (void **) &(_obj7), (void **) &(_obj8), (void **) &(_obj9), (void **) &(_obj10), (void **) &(_obj11), (void **) &(_obj12), (void **) &(_obj13), (void **) &(_obj14), (void **) &(_obj15), (void **) &(_obj16), (void **) &(_obj17), (void **) &(_obj18), (void **) &(_obj19), (void **) &(_obj20), NULL }; *_ggggc_func_pstack = _ggggc_func_pstack_tmp; ggggc_pstack = (void *) _ggggc_func_pstack; } while (0)
