#undef GGC_PUSH
#define GGC_PUSH(...)
#undef GGC_DPUSH
#define GGC_DPUSH(...)
#undef GGC_PUSH_GLOBAL
#define GGC_PUSH_GLOBAL(...)
#undef GGC_DPUSH_GLOBAL
#define GGC_DPUSH_GLOBAL(...)
#undef GGC_POP
#define GGC_POP(...)
#undef GGC_DPOP
#define GGC_DPOP(...)
#undef GGC_APOP
#define GGC_APOP(...)
#undef GGC_ASPOP
#define GGC_ASPOP(...)
#undef GGC_ADPOP
#define GGC_ADPOP(...)
#undef GGC_AAPOP
#define GGC_AAPOP(...)
#undef GGC_YIELD
#define GGC_YIELD(...)
#undef GGC_PUSH1
#define GGC_PUSH1(...)
#undef GGC_DPUSH1
#define GGC_DPUSH1(...)
#undef GGC_PUSH2
#define GGC_PUSH2(...)
#undef GGC_DPUSH2
#define GGC_DPUSH2(...)
#undef GGC_PUSH3
#define GGC_PUSH3(...)
#undef GGC_DPUSH3
#define GGC_DPUSH3(...)
#undef GGC_PUSH4
#define GGC_PUSH4(...)
#undef GGC_DPUSH4
#define GGC_DPUSH4(...)
#undef GGC_PUSH5
#define GGC_PUSH5(...)
#undef GGC_DPUSH5
#define GGC_DPUSH5(...)
#undef GGC_PUSH6
#define GGC_PUSH6(...)
#undef GGC_DPUSH6
#define GGC_DPUSH6(...)
#undef GGC_PUSH7
#define GGC_PUSH7(...)
#undef GGC_DPUSH7
#define GGC_DPUSH7(...)
#undef GGC_PUSH8
#define GGC_PUSH8(...)
#undef GGC_DPUSH8
#define GGC_DPUSH8(...)
#undef GGC_PUSH9
#define GGC_PUSH9(...)
#undef GGC_DPUSH9
#define GGC_DPUSH9(...)
#undef GGC_PUSH10
#define GGC_PUSH10(...)
#undef GGC_DPUSH10
#define GGC_DPUSH10(...)
#undef GGC_PUSH11
#define GGC_PUSH11(...)
#undef GGC_DPUSH11
#define GGC_DPUSH11(...)
#undef GGC_PUSH12
#define GGC_PUSH12(...)
#undef GGC_DPUSH12
#define GGC_DPUSH12(...)
#undef GGC_PUSH13
#define GGC_PUSH13(...)
#undef GGC_DPUSH13
#define GGC_DPUSH13(...)
#undef GGC_PUSH14
#define GGC_PUSH14(...)
#undef GGC_DPUSH14
#define GGC_DPUSH14(...)
#undef GGC_PUSH15
#define GGC_PUSH15(...)
#undef GGC_DPUSH15
#define GGC_DPUSH15(...)
#undef GGC_PUSH16
#define GGC_PUSH16(...)
#undef GGC_DPUSH16
#define GGC_DPUSH16(...)
#undef GGC_PUSH17
#define GGC_PUSH17(...)
#undef GGC_DPUSH17
#define GGC_DPUSH17(...)
#undef GGC_PUSH18
#define GGC_PUSH18(...)
#undef GGC_DPUSH18
#define GGC_DPUSH18(...)
#undef GGC_PUSH19
#define GGC_PUSH19(...)
#undef GGC_DPUSH19
#define GGC_DPUSH19(...)
#undef GGC_PUSH20
#define GGC_PUSH20(...)
#undef GGC_DPUSH20
#define GGC_DPUSH20(...)
