#include <stdio.h>

int main()
{
    int i, j;
    printf("/* this file is generated by pushgen.c. Do not edit manually. */\n"
           "#ifndef GGGGC_PUSH_H\n#define GGGGC_PUSH_H 1\n"
           "#ifdef GGGGC_NO_REDEFINE_RETURN\n"
           "#define GGGGC_LOCAL_PUSH\n"
           "#else\n"
           "#define GGGGC_LOCAL_PUSH const int ggggc_local_push = 1;\n"
           "#endif\n");
    for (i = 1; i <= 16; i++) {
        printf("#define GGC_PUSH_%d(", i);
        for (j = 0; j < i; j++) {
            if (j != 0) printf(", ");
            printf("ggggc_ptr_%c", 'a' + j);
        }
        printf(") \\\n"
               "GGGGC_LOCAL_PUSH \\\n"
               "do { \\\n"
               "    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * %d); \\\n"
               "    ggggc_pstack_cur->next = ggggc_pointerStack; \\\n"
               "    ggggc_pstack_cur->size = %d; \\\n",
               i, i);
        for (j = 0; j < i; j++) {
            printf("    ggggc_pstack_cur->pointers[%d] = &(ggggc_ptr_%c); \\\n", j, 'a' + j);
        }
        printf("    ggggc_pstack_cur->pointers[%d] = NULL; \\\n"
               "    ggggc_pointerStack = ggggc_pstack_cur; \\\n"
               "} while(0)\n", i);
    }
    printf("#define GGC_PUSH_N(n, pptrs) \\\n"
           "GGGGC_LOCAL_PUSH \\\n"
           "do { \\\n"
           "    size_t ggggc_n = (n); \\\n"
           "    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * ggggc_n); \\\n"
           "    void *ggggc_pptrs[] = (void*[]) pptrs; \\\n"
           "    ggggc_pstack_cur->next = ggggc_pointerStack; \\\n"
           "    memcpy(ggggc_pstack_cur->pointers, ggggc_pptrs, sizeof(void *) * ggggc_n); \\\n"
           "    ggggc_pstack_cur->pointers[ggggc_n] = NULL; \\\n"
           "    ggggc_pointerStack = ggggc_pstack_cur; \\\n"
           "} while(0)\n"
           "#endif\n");
    return 0;
}
