/* this file is generated by pushgen.c. Do not edit manually. */
#ifndef GGGGC_PUSH_H
#define GGGGC_PUSH_H 1
#ifdef GGGGC_NO_REDEFINE_RETURN
#define GGGGC_LOCAL_PUSH
#else
#define GGGGC_LOCAL_PUSH const int ggggc_local_push = 1;
#endif
#define GGC_PUSH_1(ggggc_ptr_a) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 1); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 1; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_2(ggggc_ptr_a, ggggc_ptr_b) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 2); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 2; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_3(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 3); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 3; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_4(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 4); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 4; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_5(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 5); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 5; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_6(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 6); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 6; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_7(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 7); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 7; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_8(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 8); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 8; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_9(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 9); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 9; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_10(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i, ggggc_ptr_j) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 10); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 10; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = &(ggggc_ptr_j); \
    ggggc_pstack_cur->pointers[10] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_11(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i, ggggc_ptr_j, ggggc_ptr_k) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 11); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 11; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = &(ggggc_ptr_j); \
    ggggc_pstack_cur->pointers[10] = &(ggggc_ptr_k); \
    ggggc_pstack_cur->pointers[11] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_12(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i, ggggc_ptr_j, ggggc_ptr_k, ggggc_ptr_l) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 12); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 12; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = &(ggggc_ptr_j); \
    ggggc_pstack_cur->pointers[10] = &(ggggc_ptr_k); \
    ggggc_pstack_cur->pointers[11] = &(ggggc_ptr_l); \
    ggggc_pstack_cur->pointers[12] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_13(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i, ggggc_ptr_j, ggggc_ptr_k, ggggc_ptr_l, ggggc_ptr_m) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 13); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 13; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = &(ggggc_ptr_j); \
    ggggc_pstack_cur->pointers[10] = &(ggggc_ptr_k); \
    ggggc_pstack_cur->pointers[11] = &(ggggc_ptr_l); \
    ggggc_pstack_cur->pointers[12] = &(ggggc_ptr_m); \
    ggggc_pstack_cur->pointers[13] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_14(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i, ggggc_ptr_j, ggggc_ptr_k, ggggc_ptr_l, ggggc_ptr_m, ggggc_ptr_n) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 14); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 14; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = &(ggggc_ptr_j); \
    ggggc_pstack_cur->pointers[10] = &(ggggc_ptr_k); \
    ggggc_pstack_cur->pointers[11] = &(ggggc_ptr_l); \
    ggggc_pstack_cur->pointers[12] = &(ggggc_ptr_m); \
    ggggc_pstack_cur->pointers[13] = &(ggggc_ptr_n); \
    ggggc_pstack_cur->pointers[14] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_15(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i, ggggc_ptr_j, ggggc_ptr_k, ggggc_ptr_l, ggggc_ptr_m, ggggc_ptr_n, ggggc_ptr_o) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 15); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 15; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = &(ggggc_ptr_j); \
    ggggc_pstack_cur->pointers[10] = &(ggggc_ptr_k); \
    ggggc_pstack_cur->pointers[11] = &(ggggc_ptr_l); \
    ggggc_pstack_cur->pointers[12] = &(ggggc_ptr_m); \
    ggggc_pstack_cur->pointers[13] = &(ggggc_ptr_n); \
    ggggc_pstack_cur->pointers[14] = &(ggggc_ptr_o); \
    ggggc_pstack_cur->pointers[15] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_16(ggggc_ptr_a, ggggc_ptr_b, ggggc_ptr_c, ggggc_ptr_d, ggggc_ptr_e, ggggc_ptr_f, ggggc_ptr_g, ggggc_ptr_h, ggggc_ptr_i, ggggc_ptr_j, ggggc_ptr_k, ggggc_ptr_l, ggggc_ptr_m, ggggc_ptr_n, ggggc_ptr_o, ggggc_ptr_p) \
GGGGC_LOCAL_PUSH \
do { \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * 16); \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    ggggc_pstack_cur->size = 16; \
    ggggc_pstack_cur->pointers[0] = &(ggggc_ptr_a); \
    ggggc_pstack_cur->pointers[1] = &(ggggc_ptr_b); \
    ggggc_pstack_cur->pointers[2] = &(ggggc_ptr_c); \
    ggggc_pstack_cur->pointers[3] = &(ggggc_ptr_d); \
    ggggc_pstack_cur->pointers[4] = &(ggggc_ptr_e); \
    ggggc_pstack_cur->pointers[5] = &(ggggc_ptr_f); \
    ggggc_pstack_cur->pointers[6] = &(ggggc_ptr_g); \
    ggggc_pstack_cur->pointers[7] = &(ggggc_ptr_h); \
    ggggc_pstack_cur->pointers[8] = &(ggggc_ptr_i); \
    ggggc_pstack_cur->pointers[9] = &(ggggc_ptr_j); \
    ggggc_pstack_cur->pointers[10] = &(ggggc_ptr_k); \
    ggggc_pstack_cur->pointers[11] = &(ggggc_ptr_l); \
    ggggc_pstack_cur->pointers[12] = &(ggggc_ptr_m); \
    ggggc_pstack_cur->pointers[13] = &(ggggc_ptr_n); \
    ggggc_pstack_cur->pointers[14] = &(ggggc_ptr_o); \
    ggggc_pstack_cur->pointers[15] = &(ggggc_ptr_p); \
    ggggc_pstack_cur->pointers[16] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#define GGC_PUSH_N(n, pptrs) \
GGGGC_LOCAL_PUSH \
do { \
    size_t ggggc_n = (n); \
    struct GGGGC_PointerStack *ggggc_pstack_cur = alloca(sizeof(struct GGGGC_PointerStack) + sizeof(void *) * ggggc_n); \
    void *ggggc_pptrs[] = (void*[]) pptrs; \
    ggggc_pstack_cur->next = ggggc_pointerStack; \
    memcpy(ggggc_pstack_cur->pointers, ggggc_pptrs, sizeof(void *) * ggggc_n); \
    ggggc_pstack_cur->pointers[ggggc_n] = NULL; \
    ggggc_pointerStack = ggggc_pstack_cur; \
} while(0)
#endif
